name: autzone
description: Civil rights social platform
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  safe_config: "^2.0.2" #http://pub.dartlang.org/packages/safe_config
  angel_framework: ^2.0.0-alpha #https://angel-dart.gitbook.io/angel/v/2.x/guides/without-the-boilerplate
  angel_static: ^2.0.0-alpha
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
  postgres: "^1.0.2" #http://pub.dartlang.org/packages/postgres
  #conn_pool: ^2.1.9 #https://pub.dartlang.org/packages/conn_pool
  intl: any #http://pub.dartlang.org/packages/intl
  timezone: any #http://pub.dartlang.org/packages/timezone
  mailer: any #http://pub.dartlang.org/packages/mailer
  diff_match_patch: any #http://pub.dartlang.org/packages/diff_match_patch
  image: any #http://pub.dartlang.org/packages/image
  http: any #http://pub.dartlang.org/packages/http
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  angel_serialize_generator: ^2.0.0
transformers:
homepage: http://www.divergentlabs.org
