name: autzone_client
description: Civil rights social platform - web client
dependencies:
  dquery: any
  js: any
  angel_serialize: ^2.0.0
  autzone_models:
    path: ../autzone_models
dev_dependencies:
  build_runner: ">=0.8.10 <2.0.0"
  build_web_compilers: ">=0.3.6 <2.0.0"
transformers:
homepage: http://www.divergentlabs.org