name: autzone_common
description: Civil rights social platform - common server functionality
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  safe_config: "^2.0.2" #http://pub.dartlang.org/packages/safe_config
  postgres: "^1.0.2" #http://pub.dartlang.org/packages/postgres
  intl: any #http://pub.dartlang.org/packages/intl
  timezone: ^0.5.2 #http://pub.dartlang.org/packages/timezone
  mailer: any #http://pub.dartlang.org/packages/mailer
  diff_match_patch: any #http://pub.dartlang.org/packages/diff_match_patch
  image: any #http://pub.dartlang.org/packages/image
  autzone_models:
    path: ../autzone_models
  http: any 
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  test: any
transformers:
homepage: http://www.divergentlabs.org 
